apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: itopw-deploy-hpa
  namespace: itopw
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout # Rollout으로 생성
    name: itopw-back-deploy
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
  resource:
    name: memory
    target:
      type: Utilization
      averageUtilization: 70
status:
  currentReplicas: 2
  desiredReplicas: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout # Rollout으로 생성
metadata:
  labels:
    app: itopw-back
  name: itopw-back-deploy
  namespace: itopw
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: itopw-back
  template:
    metadata:
      labels:
        app: itopw-back
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: itopw-back-cm
              key: SERVER_PORT
        - name: SPRING_MAIL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: itopw-back-cm
              key: SPRING_MAIL_USERNAME
        - name: SPRING_MAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: itopw-back-cm
              key: SPRING_MAIL_HOST
        - name: SPRING_MAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: itopw-back-cm
              key: SPRING_MAIL_PORT
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: itopw-back-cm
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: itopw-back-secret
              key: SPRING_DATASOURCE_URL
        - name: SPRING_MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: itopw-back-secret
              key: SPRING_MAIL_PASSWORD
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: itopw-back-secret
              key: SPRING_DATASOURCE_PASSWORD
        image: dialee/itopw-back:v0.0.0
        name: itopw-back
        ports:
        - containerPort: 8081
          name: itopw-back
        resources:
          limits:
            cpu: 800m
            memory: 800M
          requests:
            cpu: 500m
            memory: 600M
        volumeMounts:
        - name: tz-seoul
          mountPath: /etc/localtime
        - name: itopw-back-volume
          mountPath: /app/images/uploads/profile-images
      volumes:
      - name: tz-seoul
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
      - name: itopw-back-volume
        persistentVolumeClaim:
          claimName: itopw-back-pvc
      restartPolicy: Always
  strategy:
    canary:
      maxSurge: "100%"    # canary 배포로 생성할 pod의 비율
      maxUnavailable: 0  # 업데이트 될 때 사용할 수 없는 pod의 최대 수
      steps:
      - setWeight: 25  # 첫 번째 단계에서 25% 트래픽 전송
      - pause: { duration: 10m }
      - setWeight: 50  # 두 번째 단계에서 50% 트래픽 전송
      - pause: { duration: 10m }
      - setWeight: 100 # 마지막 단계에서 100% 트래픽 전송
