apiVersion: v1
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vaXRvcHctZGItc3ZjOjU0MzIvaXRvcHc=
  SPRING_DATASOURCE_PASSWORD: MzBjK3JuZmpkZGw=
kind: Secret
metadata:
  creationTimestamp: null
  name: itopw-back-secret
  namespace: itopw
