apiVersion: v1
kind: Service
metadata:
  labels:
    app: itopw-back
  name: itopw-back-svc
  namespace: itopw
spec:
  type: ClusterIP
  ports:
  - port: 8081
    name: itopw-back-svc
    targetPort: 8081
    protocol: TCP
  selector:
    app: itopw-back
