apiVersion: v1
kind: PersistentVolume
metadata:
  name: itopw-back-pv
  namespace: itopw
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /itopw/profile-images
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itopw-back-pvc
  namespace: itopw
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
