apiVersion: v1
kind: ConfigMap
metadata:
  namespace: itopw
  name: itopw-front-cm
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        #access_log  /var/log/nginx/host.access.log  main;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.html;
            try_files $uri $uri/ /index.html =404;
        }
        
        
        location /api {
            proxy_pass http://itopw-back-svc:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /images {
            proxy_pass http://itopw-back-svc:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            alias /app/images/; # 백엔드의 /app/images 경로를 사용
            autoindex on; # 디렉터리 브라우징 활성화 (옵션)
        }

        location /images/uploads/profile-images {
            default_type image/png; # Content-Type 설정 (옵션)
            proxy_pass http://itopw-back-svc:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            root /app; # 이 경로는 /app/images/uploads/profile-images/로 매핑
            #alias /app/images/uploads/profile-images; # 백엔드의 /app/images 경로를 사용
            autoindex on; # 디렉터리 브라우징 활성화 (옵션)
            types {
                image/png png;
                image/jpeg jpg jpeg;
                image/gif gif;
                image/svg+xml svg;
            }
        }

        

        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

