apiVersion: v1
kind: Service
metadata:
  name: itopw-front-svc
  namespace: itopw
spec:
  selector:
    app: itopw-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
