apiVersion: kustomize.config.k8s.io/v1
resources:
- itopw-front-deploy.yaml
- itopw-front-svc.yaml
kind: Kustomization
images:
- name: dialee/itopw-front
  newTag: v0.0.4-v0-0-4-v0-0-4-v0-0-4-v0-0-4-v0-0-4-v0-0-3-0-0-0-0-0.0
